language: csharp

dotnet: 2.1.402

mono:
  - 5.2.0

install:
  - mozroots --import --sync
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.1.402
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet: 2.1.402
      dist: trusty
      sudo: required

script: 
  - dotnet --info
  - dotnet restore
  - dotnet build -c Release
  - dotnet test --no-build -c Release tests/Freya.Routers.Uri.Template.Tests/Freya.Routers.Uri.Template.Tests.fsproj
  - dotnet test --no-build -c Release tests/Freya.Routers.Uri.Template.Hopac.Tests/Freya.Routers.Uri.Template.Hopac.Tests.fsproj
  - dotnet pack --no-build -c Release --include-symbols
  - dotnet benchmarks/Freya.Routers.Uri.Template.Benchmarks/bin/Release/netcoreapp2.1/Freya.Routers.Uri.Template.Benchmarks.dll

branches:
  except:
    - gh-pages
